# Generated by Django 5.1.6 on 2025-02-21 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="notificator_is_on",
            field=models.BooleanField(
                default=True, verbose_name="Подключение уведомлений"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="tg_chat_id",
            field=models.CharField(
                blank=True,
                max_length=9,
                null=True,
                unique=True,
                verbose_name="ID пользователя в Телеграм",
            ),
        ),
    ]
