# Generated by Django 5.1.6 on 2025-02-23 11:30

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "place",
                    models.CharField(max_length=100, verbose_name="Место выполнения"),
                ),
                ("time", models.TimeField(verbose_name="Время выполнения")),
                ("action", models.CharField(max_length=250, verbose_name="Действие")),
                (
                    "is_enjoyable",
                    models.BooleanField(default=False, verbose_name="Приятность"),
                ),
                (
                    "period",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Периодичность (в днях)"
                    ),
                ),
                (
                    "fee",
                    models.CharField(
                        blank=True,
                        null=True,
                        verbose_name="Вознаграждение за выполненную привычку",
                    ),
                ),
                (
                    "action_time",
                    models.DurationField(
                        default=datetime.timedelta(seconds=120),
                        verbose_name="Время на выполнение",
                    ),
                ),
                ("is_public", models.BooleanField(verbose_name="Публичность")),
                (
                    "last_notified",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Время последнего уведомления",
                    ),
                ),
                (
                    "associated_habit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tracker.habit",
                        verbose_name="Связанная привычка",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создатель",
                    ),
                ),
            ],
        ),
    ]
