# Generated by Django 5.1.6 on 2025-02-20 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="fee",
            field=models.CharField(
                blank=True,
                null=True,
                verbose_name="Вознаграждение за выполненную привычку",
            ),
        ),
    ]
