# Generated by Django 5.1.6 on 2025-02-20 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0003_alter_habit_fee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="period",
            field=models.PositiveSmallIntegerField(
                default=1, verbose_name="Периодичность"
            ),
        ),
    ]
