# Generated by Django 5.1.6 on 2025-02-20 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0004_alter_habit_period"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="period",
            field=models.PositiveIntegerField(default=1, verbose_name="Периодичность"),
        ),
    ]
