# Generated by Django 5.1.6 on 2025-02-21 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0005_alter_habit_period"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="last_notified",
            field=models.DateField(
                blank=True, null=True, verbose_name="Время последнего уведомления"
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="period",
            field=models.PositiveIntegerField(
                default=1, verbose_name="Периодичность (в днях)"
            ),
        ),
    ]
